### ISSUE TITLE
Cannot use commands on WidgetBot

### ISSUE THREAD

**Issue by SuzianeCundiff** [UltimateBrent/discord-rod#30]
I'm using WidgetBot on a website and one of the requests is to make possible to use RoD Bot commands, but when I try the command is read as a simple message.

First I make contact with Widgetbot's creator and he replied with:

- users cannot use slash commands from WidgetBot; it is not possible for us to add bot slash commands to the widget due to a Discord limitation

- for old message-based bot commands, the bot can see messages sent through WidgetBot, but it may be choosing to ignore it. You'll need to talk to the developers of rod-bot for more information.

So, now I'm here :)
Is it possible to fix it?

**Comment by UltimateBrent** [comment]
I have no idea what Widgetbot is, can you link to it?

**Comment by SuzianeCundiff** [comment]
Sorry, I totally forgot the link
[Widgetbot](https://widgetbot.io/)

**Comment by UltimateBrent** [comment]
I'm not sure if you could automate this, but other bots can talk to Rod by prepending the message with `|rod-bot|`. So something like `|rod-bot|.roll d20` should work just fine. Some things might not work well because they expect an actual user to say them, but it's the only real answer here. I can't blanket open Rod to other bots, or there'll be infinite loops of chaos on some servers.
